# Generated by Django 5.2.6 on 2025-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_usuario_remove_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_inscripcion',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_leccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
